name: Test

on: 
  push:
    branches-ignore:
      - master
  pull_request: {}
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Toolchain 1.48.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48.0
          default: true

      - name: Build
        run: cargo build --verbose
        working-directory: ./test

      - name: Run tests
        run: cargo test --verbose
        working-directory: ./test
